version: '3.8'
volumes:
  data:
networks: 
  db_network:
services:
  db:
    image: mariadb:10.5.8
    restart: always
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - data:/var/lib/mysql
    networks:
      - db_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: improve_your_vocabulary
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    networks:
      - db_network
    ports:
      - 8001:80
    environment:
      MYSQL_ROOT_PASSWORD: root